// <auto-generated />
using Kamban.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kamban.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kamban.Models.ScrumTask", b =>
                {
                    b.Property<int>("ScrumTaskId")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ScrumTaskId");

                    b.ToTable("VendrediScrumTasks");

                    b.HasData(
                        new
                        {
                            ScrumTaskId = 1,
                            Category = 0,
                            Description = "Used to develop computer programs, web services, and mobile applications. ",
                            Title = "Microsoft Visual Studio",
                            UserId = 2
                        },
                        new
                        {
                            ScrumTaskId = 2,
                            Category = 2,
                            Description = "Gaming console released in 2001",
                            Title = "Xbox 360",
                            UserId = 1
                        },
                        new
                        {
                            ScrumTaskId = 3,
                            Category = 1,
                            Description = "The launch of Microsoft Word, followed by Excel, and Powerpoint in the mid-1980s ",
                            Title = "Microsoft Office",
                            UserId = 3
                        },
                        new
                        {
                            ScrumTaskId = 4,
                            Category = 0,
                            Description = "The creation and release of Internet Explorer in 1995",
                            Title = "Internet Explorer",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Kamban.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UsersVendredi");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Name = "Timothy"
                        },
                        new
                        {
                            UserId = 2,
                            Name = "Francis"
                        },
                        new
                        {
                            UserId = 3,
                            Name = "Ruben"
                        },
                        new
                        {
                            UserId = 4,
                            Name = "Mauro"
                        },
                        new
                        {
                            UserId = 5,
                            Name = "Jarno"
                        });
                });

            modelBuilder.Entity("Kamban.Models.ScrumTask", b =>
                {
                    b.HasOne("Kamban.Models.User", "User")
                        .WithMany("ScrumTasks")
                        .HasForeignKey("ScrumTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kamban.Models.User", b =>
                {
                    b.Navigation("ScrumTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
